// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameActor = "actor"

// Actor mapped from table <actor>
type Actor struct {
	ActorID    int32     `gorm:"column:actor_id;primaryKey;autoIncrement:true" json:"actor_id"`
	FirstName  string    `gorm:"column:first_name;not null" json:"first_name"`
	LastName   string    `gorm:"column:last_name;not null" json:"last_name"`
	LastUpdate time.Time `gorm:"column:last_update;not null;default:now()" json:"last_update"`
}

// TableName Actor's table name
func (*Actor) TableName() string {
	return TableNameActor
}
