// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAddress = "address"

// Address mapped from table <address>
type Address struct {
	AddressID  int32     `gorm:"column:address_id;primaryKey;autoIncrement:true" json:"address_id"`
	Address    string    `gorm:"column:address;not null" json:"address"`
	Address2   string    `gorm:"column:address2" json:"address2"`
	District   string    `gorm:"column:district;not null" json:"district"`
	CityID     int16     `gorm:"column:city_id;not null" json:"city_id"`
	PostalCode string    `gorm:"column:postal_code" json:"postal_code"`
	Phone      string    `gorm:"column:phone;not null" json:"phone"`
	LastUpdate time.Time `gorm:"column:last_update;not null;default:now()" json:"last_update"`
}

// TableName Address's table name
func (*Address) TableName() string {
	return TableNameAddress
}
