// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBasketA = "basket_a"

// BasketA mapped from table <basket_a>
type BasketA struct {
	A      int32  `gorm:"column:a;primaryKey" json:"a"`
	FruitA string `gorm:"column:fruit_a;not null" json:"fruit_a"`
}

// TableName BasketA's table name
func (*BasketA) TableName() string {
	return TableNameBasketA
}
