// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBasketB = "basket_b"

// BasketB mapped from table <basket_b>
type BasketB struct {
	B      int32  `gorm:"column:b;primaryKey" json:"b"`
	FruitB string `gorm:"column:fruit_b;not null" json:"fruit_b"`
}

// TableName BasketB's table name
func (*BasketB) TableName() string {
	return TableNameBasketB
}
