// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCategory = "category"

// Category mapped from table <category>
type Category struct {
	CategoryID int32     `gorm:"column:category_id;primaryKey;autoIncrement:true" json:"category_id"`
	Name       string    `gorm:"column:name;not null" json:"name"`
	LastUpdate time.Time `gorm:"column:last_update;not null;default:now()" json:"last_update"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
