// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCity = "city"

// City mapped from table <city>
type City struct {
	CityID     int32     `gorm:"column:city_id;primaryKey;autoIncrement:true" json:"city_id"`
	City       string    `gorm:"column:city;not null" json:"city"`
	CountryID  int16     `gorm:"column:country_id;not null" json:"country_id"`
	LastUpdate time.Time `gorm:"column:last_update;not null;default:now()" json:"last_update"`
}

// TableName City's table name
func (*City) TableName() string {
	return TableNameCity
}
