// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCountry = "country"

// Country mapped from table <country>
type Country struct {
	CountryID  int32     `gorm:"column:country_id;primaryKey;autoIncrement:true" json:"country_id"`
	Country    string    `gorm:"column:country;not null" json:"country"`
	LastUpdate time.Time `gorm:"column:last_update;not null;default:now()" json:"last_update"`
}

// TableName Country's table name
func (*Country) TableName() string {
	return TableNameCountry
}
