// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCustomer = "customer"

// Customer mapped from table <customer>
type Customer struct {
	CustomerID int32     `gorm:"column:customer_id;primaryKey;autoIncrement:true" json:"customer_id"`
	StoreID    int16     `gorm:"column:store_id;not null" json:"store_id"`
	FirstName  string    `gorm:"column:first_name;not null" json:"first_name"`
	LastName   string    `gorm:"column:last_name;not null" json:"last_name"`
	Email      string    `gorm:"column:email" json:"email"`
	AddressID  int16     `gorm:"column:address_id;not null" json:"address_id"`
	Activebool bool      `gorm:"column:activebool;not null;default:true" json:"activebool"`
	CreateDate time.Time `gorm:"column:create_date;not null;default:('now'::text)::date" json:"create_date"`
	LastUpdate time.Time `gorm:"column:last_update;default:now()" json:"last_update"`
	Active     int32     `gorm:"column:active" json:"active"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
