// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFilmActor = "film_actor"

// FilmActor mapped from table <film_actor>
type FilmActor struct {
	ActorID    int16     `gorm:"column:actor_id;primaryKey" json:"actor_id"`
	FilmID     int16     `gorm:"column:film_id;primaryKey" json:"film_id"`
	LastUpdate time.Time `gorm:"column:last_update;not null;default:now()" json:"last_update"`
}

// TableName FilmActor's table name
func (*FilmActor) TableName() string {
	return TableNameFilmActor
}
