// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFilmCategory = "film_category"

// FilmCategory mapped from table <film_category>
type FilmCategory struct {
	FilmID     int16     `gorm:"column:film_id;primaryKey" json:"film_id"`
	CategoryID int16     `gorm:"column:category_id;primaryKey" json:"category_id"`
	LastUpdate time.Time `gorm:"column:last_update;not null;default:now()" json:"last_update"`
}

// TableName FilmCategory's table name
func (*FilmCategory) TableName() string {
	return TableNameFilmCategory
}
