// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInventory = "inventory"

// Inventory mapped from table <inventory>
type Inventory struct {
	InventoryID int32     `gorm:"column:inventory_id;primaryKey;autoIncrement:true" json:"inventory_id"`
	FilmID      int16     `gorm:"column:film_id;not null" json:"film_id"`
	StoreID     int16     `gorm:"column:store_id;not null" json:"store_id"`
	LastUpdate  time.Time `gorm:"column:last_update;not null;default:now()" json:"last_update"`
}

// TableName Inventory's table name
func (*Inventory) TableName() string {
	return TableNameInventory
}
