// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePayment = "payment"

// Payment mapped from table <payment>
type Payment struct {
	PaymentID   int32     `gorm:"column:payment_id;primaryKey;autoIncrement:true" json:"payment_id"`
	CustomerID  int16     `gorm:"column:customer_id;not null" json:"customer_id"`
	StaffID     int16     `gorm:"column:staff_id;not null" json:"staff_id"`
	RentalID    int32     `gorm:"column:rental_id;not null" json:"rental_id"`
	Amount      float64   `gorm:"column:amount;not null" json:"amount"`
	PaymentDate time.Time `gorm:"column:payment_date;not null" json:"payment_date"`
}

// TableName Payment's table name
func (*Payment) TableName() string {
	return TableNamePayment
}
