// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRental = "rental"

// Rental mapped from table <rental>
type Rental struct {
	RentalID    int32     `gorm:"column:rental_id;primaryKey;autoIncrement:true" json:"rental_id"`
	RentalDate  time.Time `gorm:"column:rental_date;not null" json:"rental_date"`
	InventoryID int32     `gorm:"column:inventory_id;not null" json:"inventory_id"`
	CustomerID  int16     `gorm:"column:customer_id;not null" json:"customer_id"`
	ReturnDate  time.Time `gorm:"column:return_date" json:"return_date"`
	StaffID     int16     `gorm:"column:staff_id;not null" json:"staff_id"`
	LastUpdate  time.Time `gorm:"column:last_update;not null;default:now()" json:"last_update"`
}

// TableName Rental's table name
func (*Rental) TableName() string {
	return TableNameRental
}
