// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStaff = "staff"

// Staff mapped from table <staff>
type Staff struct {
	StaffID    int32     `gorm:"column:staff_id;primaryKey;autoIncrement:true" json:"staff_id"`
	FirstName  string    `gorm:"column:first_name;not null" json:"first_name"`
	LastName   string    `gorm:"column:last_name;not null" json:"last_name"`
	AddressID  int16     `gorm:"column:address_id;not null" json:"address_id"`
	Email      string    `gorm:"column:email" json:"email"`
	StoreID    int16     `gorm:"column:store_id;not null" json:"store_id"`
	Active     bool      `gorm:"column:active;not null;default:true" json:"active"`
	Username   string    `gorm:"column:username;not null" json:"username"`
	Password   string    `gorm:"column:password" json:"password"`
	LastUpdate time.Time `gorm:"column:last_update;not null;default:now()" json:"last_update"`
	Picture    []uint8   `gorm:"column:picture" json:"picture"`
}

// TableName Staff's table name
func (*Staff) TableName() string {
	return TableNameStaff
}
