// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Password  string    `gorm:"column:password;not null" json:"password"`
	Email     string    `gorm:"column:email;not null" json:"email"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
	Role      string    `gorm:"column:role;not null;default:regular" json:"role"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
