// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Created        time.Time `gorm:"column:created;not null" json:"created"`
	Email          string    `gorm:"column:email;not null" json:"email"`
	HashedPassword string    `gorm:"column:hashed_password;not null" json:"hashed_password"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
